version: "3"
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
